# Generated by Django 4.2.13 on 2024-06-21 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='prompt',
            field=models.TextField(),
        ),
    ]
