# Generated by Django 4.2.13 on 2024-06-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_alter_detail_prompt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
